name: Tmap Build

on:
  workflow_dispatch:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: wget
        uses: wei/wget@v1
        with:
          args: -O apktool.jar  https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.6.1.jar
        
      - name: wget
        uses: wei/wget@v1
        with:
          args: -O uber-apk-signer.jar  https://github.com/patrickfav/uber-apk-signer/releases/download/v1.2.1/uber-apk-signer-1.2.1.jar     
        
        
        
      - name: build
        run: |
             java -jar apktool.jar b . --use-aapt2 
             java -jar uber-apk-signer.jar -a dist/* -allowResign --overwrite
        
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Release ${{ env.date_now }}"
          files: |
            dist/*.apk
